name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: download dbus repo
    - run: wget http://dbus.freedesktop.org/releases/dbus/dbus-1.9.0.tar.gz

