name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: download dbus repo
      run: |
          mkdir _dbus && cd _dbus
          wget http://dbus.freedesktop.org/releases/dbus/dbus-1.9.0.tar.gz
          tar -xzf dbus-1.9.0.tar.gz
          cd dbus-1.9.0
          echo "list all patches in the folder "
          for filename in ../../src/dbus-patches/*; do patch -p1 < ${filename}; done
          
          ./configure --prefix=$PWD/_libs
          make -C dbus 
          make -C dbus install
          make install-pkgconfigDATA
          echo "list all dbus libs built now : " && ls $PWD/_libs/lib
  download-dependencies: 
    runs-on: ubuntu-latest
    steps:
    
    - name: Download artifact from build
    - uses: actions/checkout@master
      with:
        repo: https://github.com/blguru20/capicxx-core-runtime
        artifact_name: my-artifact   
        wait_seconds: 60
           
          

