name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 2
    - name: download dbus repo
    
      run: |
          mkdir _dbus && cd _dbus
          wget http://dbus.freedesktop.org/releases/dbus/dbus-1.9.0.tar.gz
          tar -xzf dbus-1.9.0.tar.gz
          cd dbus-1.9.0
          echo "list all patches in the folder "
          for filename in ../../src/dbus-patches/*; do patch -p1 < ${filename}; done
          
          ./configure --prefix=$PWD/_libs
          make -C dbus 
          make -C dbus install
          make install-pkgconfigDATA
          echo "list all dbus libs built now : " && ls $PWD/_libs/lib
  download-dependencies: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
         repository: blguru20/capicxx-core-runtime
         artifact_name: libCommonAPI.so.3.2.0
       
  run-clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run clang format for git diff 
      run: | 
        sudo apt-get install -y git
        git --version
        echo "Path is ... $PATH"
        PATH=$PATH:$(which git)
        echo "Path is ... $PATH"
        sudo apt install clang-format
        git commit --allow-empty -n -m "Initial commit."
        git clang-format HEAD~1 HEAD --diff  --style=file 

